### ISSUE TITLE
feat: 종료된 모임에 대한 처리 로직 추가

### ISSUE THREAD

**Issue by Dawon00** [dnd-side-project/dnd-11th-6-frontend#92]
## 현재 상황
현재 운영이 종료된 모임에 대해 접근했을 때 정상적으로 닉네임 입력 페이지까지 이동이 가능합니다.

## 목표

- [ ] 종료된 모임에 대해 예외 처리를 구현
- [ ] 종료된 모임에 대한 ui 별도로 추가

**Comment by jiji-hoon96** [comment]
<img width="329" alt="스크린샷 2024-09-15 오후 1 07 10" src="https://github.com/user-attachments/assets/ec60ebea-171c-4462-a888-ff031a5c4053">

위 스샷을 보니 api에서 끝난 모임의 status가 200이네요!
확인 부탁드립니다!
